// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUxVzIqRL82oEeO6UV9tzQ0YDXChBm5OM',
    appId: '1:736711467147:web:1446206559d214b48db48e',
    messagingSenderId: '736711467147',
    projectId: 'whatsapp-clone-958d1',
    authDomain: 'whatsapp-clone-958d1.firebaseapp.com',
    storageBucket: 'whatsapp-clone-958d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHyuFnI9xoufGOhX59h-3zDlFgq09Zb8',
    appId: '1:736711467147:android:6124f2b2869530b98db48e',
    messagingSenderId: '736711467147',
    projectId: 'whatsapp-clone-958d1',
    storageBucket: 'whatsapp-clone-958d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Rw5KG9GtNpGbEN6aXs7s1pKTmAIRZnU',
    appId: '1:736711467147:ios:53392d586d8450e18db48e',
    messagingSenderId: '736711467147',
    projectId: 'whatsapp-clone-958d1',
    storageBucket: 'whatsapp-clone-958d1.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Rw5KG9GtNpGbEN6aXs7s1pKTmAIRZnU',
    appId: '1:736711467147:ios:53392d586d8450e18db48e',
    messagingSenderId: '736711467147',
    projectId: 'whatsapp-clone-958d1',
    storageBucket: 'whatsapp-clone-958d1.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUxVzIqRL82oEeO6UV9tzQ0YDXChBm5OM',
    appId: '1:736711467147:web:81ebca0590ca62498db48e',
    messagingSenderId: '736711467147',
    projectId: 'whatsapp-clone-958d1',
    authDomain: 'whatsapp-clone-958d1.firebaseapp.com',
    storageBucket: 'whatsapp-clone-958d1.firebasestorage.app',
  );
}
